export type ConstantCategory = 'mechanics' | 'em' | 'quantum' | 'atomic' | 'thermo' | 'cosmology';

export interface PhysicalConstant {
  symbol: string;
  latexSymbol?: string;
  name: string;
  value: string;
  units: string;
  uncertainty: string;
  category: ConstantCategory;
  story: string;
  related?: string[];
}

export const CATEGORY_LABELS: Record<ConstantCategory, string> = {
  mechanics:  'Mechanics & Gravity',
  em:         'Electromagnetism',
  quantum:    'Quantum & Atomic',
  atomic:     'Atomic Structure',
  thermo:     'Thermodynamics',
  cosmology:  'Cosmology',
};

export const CATEGORY_COLORS: Record<ConstantCategory, string> = {
  mechanics:  '#3b82f6',
  em:         '#a855f7',
  quantum:    '#ec4899',
  atomic:     '#eab308',
  thermo:     '#f97316',
  cosmology:  '#06b6d4',
};

export const constants: PhysicalConstant[] = [
  {
    symbol: 'c',
    name: 'Speed of light in vacuum',
    value: '299 792 458',
    units: 'm/s',
    uncertainty: 'exact',
    category: 'em',
    story: 'In 1983, the meter was redefined so that c is exact by construction: a meter is the distance light travels in 1/299,792,458 of a second. Measuring c more precisely would now change the definition of the meter, not the value of c. The constant that Rømer estimated by watching Jupiter\'s moons in 1676 — getting within 30% — is now a definition.',
    related: ['/electromagnetism/maxwell', '/modern/relativity'],
  },
  {
    symbol: 'h',
    name: 'Planck constant',
    value: '6.626 070 15 × 10⁻³⁴',
    units: 'J·s',
    uncertainty: 'exact (since 2019)',
    category: 'quantum',
    story: 'Planck invented his constant in 1900 as a "calculational trick" — he assumed energy came in discrete chunks to derive a formula that fit blackbody radiation data, then spent years trying to get rid of the assumption. He couldn\'t. Since the 2019 SI revision, h is an exact number by definition, and the kilogram is now defined in terms of h through the Kibble balance.',
    related: ['/modern/quantum'],
  },
  {
    symbol: 'ℏ',
    name: 'Reduced Planck constant',
    value: '1.054 571 817 × 10⁻³⁴',
    units: 'J·s',
    uncertainty: 'exact (since 2019)',
    category: 'quantum',
    story: 'ℏ = h/2π appears naturally in quantum mechanics wherever angular frequency ω is more natural than ordinary frequency f. Dirac introduced the notation ℏ ("h-bar") to avoid writing h/2π constantly. It sets the scale at which quantum effects become important: systems with action much larger than ℏ behave classically.',
    related: ['/modern/quantum', '/mechanics/hamiltonian'],
  },
  {
    symbol: 'e',
    name: 'Elementary charge',
    value: '1.602 176 634 × 10⁻¹⁹',
    units: 'C',
    uncertainty: 'exact (since 2019)',
    category: 'em',
    story: 'Millikan measured the elementary charge to within 0.5% in 1909 using charged oil droplets falling through an electric field — and initially got the wrong answer because he used the wrong value for air viscosity. The correct answer was reported by Ehrenhaft first, but Millikan\'s cleaner data won out. Since 2019, e is an exact number by definition, anchoring the ampere.',
    related: ['/electromagnetism/fields', '/modern/atomic'],
  },
  {
    symbol: 'G',
    name: 'Gravitational constant',
    value: '6.674 30 × 10⁻¹¹',
    units: 'N·m²/kg²',
    uncertainty: '22 ppm',
    category: 'mechanics',
    story: 'G is the most imprecisely known fundamental constant — uncertain to about 22 parts per million, a thousand times worse than other constants. Two careful lab measurements made in the same decade disagreed by 40 ppm, outside each other\'s stated uncertainties. Unlike c, e, and h, G cannot be linked to quantum properties, so we measure it mechanically with torsion balances. Precision mechanics is hard.',
    related: ['/mechanics/gravitation'],
  },
  {
    symbol: 'kB',
    name: 'Boltzmann constant',
    value: '1.380 649 × 10⁻²³',
    units: 'J/K',
    uncertainty: 'exact (since 2019)',
    category: 'thermo',
    story: 'Boltzmann\'s constant converts between the macroscopic unit of temperature (kelvin) and the microscopic unit of energy (joule). Since 2019, the kelvin is defined by fixing kB to this exact value — temperature is now defined as a measure of average kinetic energy, not by a triple point of water. Boltzmann himself never calculated the constant; it was first measured by Planck from blackbody data in 1900.',
    related: ['/thermodynamics/statistical', '/thermodynamics/laws'],
  },
  {
    symbol: 'NA',
    name: 'Avogadro constant',
    value: '6.022 140 76 × 10²³',
    units: 'mol⁻¹',
    uncertainty: 'exact (since 2019)',
    category: 'thermo',
    story: 'Avogadro never calculated the number that bears his name — he only proposed in 1811 that equal volumes of gases contain equal numbers of molecules. The number was first estimated by Loschmidt in 1865 from gas viscosity. Since 2019, a mole is defined as exactly 6.022140076×10²³ entities, making NA an exact number and the atomic mass unit precisely anchored.',
    related: ['/thermodynamics/gas-laws', '/thermodynamics/statistical'],
  },
  {
    symbol: 'ε₀',
    name: 'Vacuum permittivity',
    value: '8.854 187 8128 × 10⁻¹²',
    units: 'F/m',
    uncertainty: '1.5 × 10⁻¹⁰',
    category: 'em',
    story: 'Vacuum permittivity is not independently fundamental — it\'s derived from c and μ₀ via ε₀ = 1/(μ₀c²). Before 2019, μ₀ was exactly 4π×10⁻⁷ by definition, making ε₀ also exact. The 2019 SI revision gave both a small measured uncertainty. ε₀ sets the strength of the electrostatic force: the factor 1/(4πε₀) in Coulomb\'s law equals Coulomb\'s constant k ≈ 8.99×10⁹ N·m²/C².',
    related: ['/electromagnetism/fields', '/electromagnetism/maxwell'],
  },
  {
    symbol: 'μ₀',
    name: 'Vacuum permeability',
    value: '1.256 637 0621 × 10⁻⁶',
    units: 'T·m/A',
    uncertainty: '1.5 × 10⁻¹⁰',
    category: 'em',
    story: 'Before 2019, μ₀ was exactly 4π×10⁻⁷ T·m/A by definition — a consequence of how the ampere was defined. The 2019 SI revision made μ₀ a measured quantity, introducing a tiny uncertainty. This was philosophically significant: one of the few cases where a redefinition made something less precise in order to make everything else more consistent.',
    related: ['/electromagnetism/magnetism', '/electromagnetism/maxwell'],
  },
  {
    symbol: 'mₑ',
    name: 'Electron mass',
    value: '9.109 383 7015 × 10⁻³¹',
    units: 'kg',
    uncertainty: '3.0 × 10⁻¹⁰',
    category: 'atomic',
    story: 'Measured to 0.3 ppb precision using Penning trap mass spectrometry — single electrons trapped in magnetic fields for weeks at a time. The ratio mₑ/mₚ ≈ 1/1836 is one of the unexplained numbers in physics: we have no deep theoretical reason why the proton should be 1836 times heavier than the electron. It just is.',
    related: ['/modern/atomic', '/modern/quantum'],
  },
  {
    symbol: 'mₚ',
    name: 'Proton mass',
    value: '1.672 621 923 69 × 10⁻²⁷',
    units: 'kg',
    uncertainty: '5.1 × 10⁻¹⁰',
    category: 'atomic',
    story: 'The proton is not a fundamental particle — it is made of two up quarks and one down quark, bound by gluons. The bare quark masses account for only about 1% of the proton\'s mass; the rest comes from the kinetic energy and field energy of the gluons via E = mc². The proton\'s mass is one of the best-tested predictions of quantum chromodynamics.',
    related: ['/modern/nuclear', '/modern/atomic'],
  },
  {
    symbol: 'α',
    name: 'Fine-structure constant',
    value: '7.297 352 5693 × 10⁻³',
    units: 'dimensionless',
    uncertainty: '1.5 × 10⁻¹⁰',
    category: 'quantum',
    story: 'α = e²/(4πε₀ℏc) ≈ 1/137 is the dimensionless number that governs the strength of electromagnetism. Feynman called it "the mystery number" and said every physicist should have it on their wall and lose sleep over it. Its value cannot be derived from any known theory — it is simply a parameter of our universe. If it were much larger, atoms would not be stable; if much smaller, chemistry would not work.',
    related: ['/modern/atomic', '/modern/quantum', '/electromagnetism/fields'],
  },
  {
    symbol: 'a₀',
    name: 'Bohr radius',
    value: '5.291 772 109 03 × 10⁻¹¹',
    units: 'm',
    uncertainty: '1.5 × 10⁻¹⁰',
    category: 'atomic',
    story: 'The Bohr radius is the most probable distance between the electron and proton in the hydrogen ground state, and the natural unit of atomic length. It can be written entirely in terms of other constants: a₀ = ℏ²/(mₑe²k) = 4πε₀ℏ²/(mₑe²). That it comes out to about 0.5 Å — roughly the size chemists expect atoms to be — was one of the first great validations of quantum mechanics.',
    related: ['/modern/atomic', '/modern/quantum'],
  },
  {
    symbol: 'R∞',
    name: 'Rydberg constant',
    value: '1.097 373 156 8160 × 10⁷',
    units: 'm⁻¹',
    uncertainty: '1.9 × 10⁻¹²',
    category: 'atomic',
    story: 'The Rydberg constant is the most precisely measured physical constant, known to 1.9 × 10⁻¹² relative uncertainty. It can be pinned down so well because hydrogen spectral lines are extremely sharp: the transition frequency from level n to level m is R∞c(1/m² − 1/n²), and frequency can be measured by counting oscillations. The proton radius puzzle — a 2010 discrepancy in measurements using muonic hydrogen — briefly suggested R∞ might need correction, and was eventually resolved.',
    related: ['/modern/atomic'],
  },
  {
    symbol: 'σ',
    name: 'Stefan-Boltzmann constant',
    value: '5.670 374 419 × 10⁻⁸',
    units: 'W·m⁻²·K⁻⁴',
    uncertainty: 'exact (since 2019)',
    category: 'thermo',
    story: 'σ = 2π⁵kB⁴/(15h³c²) connects thermal radiation to the other constants of nature. Stefan found the T⁴ power law empirically in 1879; Boltzmann derived it from thermodynamics in 1884 — five years before anyone knew the right microscopic picture. Planck\'s full derivation in 1900 required inventing quantum mechanics along the way.',
    related: ['/thermodynamics/heat', '/modern/quantum'],
  },
  {
    symbol: 'R',
    name: 'Molar gas constant',
    value: '8.314 462 618',
    units: 'J/(mol·K)',
    uncertainty: 'exact (since 2019)',
    category: 'thermo',
    story: 'R = NA × kB is the bridge between macroscopic chemistry (PV = nRT) and microscopic physics. Since 2019, both NA and kB are exact, making R exact. The value 8.314 J/(mol·K) means that one mole of an ideal gas at room temperature (298 K) has about 2.5 kJ of thermal energy — which is why a calorie is roughly 4 J and chemical energy scales are in kJ/mol.',
    related: ['/thermodynamics/gas-laws', '/thermodynamics/statistical'],
  },
  {
    symbol: 'eV',
    name: 'Electron volt',
    value: '1.602 176 634 × 10⁻¹⁹',
    units: 'J',
    uncertainty: 'exact (since 2019)',
    category: 'quantum',
    story: 'One electron volt is the kinetic energy gained by an electron accelerating through 1 volt of potential difference. It is the natural energy unit for atomic and nuclear physics: chemical bonds are a few eV, X-ray photons are keV, nuclear transitions are MeV, LHC collisions reach TeV. The fact that room temperature corresponds to kBT ≈ 1/40 eV ≈ 25 meV is why chemical reactions need activation energies of order 1 eV to proceed without a catalyst.',
    related: ['/modern/atomic', '/modern/quantum', '/electromagnetism/fields'],
  },
  {
    symbol: 'H₀',
    name: 'Hubble constant',
    value: '~67–73',
    units: 'km/s/Mpc',
    uncertainty: '~2% (tension unresolved)',
    category: 'cosmology',
    story: 'The Hubble constant measures the current expansion rate of the universe. The embarrassing problem is that two independent methods give different answers: the cosmic microwave background gives 67.4 km/s/Mpc, while distance-ladder measurements give 73 km/s/Mpc. The 5σ discrepancy, called the "Hubble tension," is one of the outstanding unsolved problems in cosmology. Either the measurements have unidentified systematic errors, or our cosmological model is incomplete.',
    related: ['/modern/relativity'],
  },
];
