export type FieldNote = {
  year?: string;
  title: string;
  body: string;
  source?: string;
  sourceUrl?: string;
};

const source = (sourceText: string, sourceUrl?: string) => ({ source: sourceText, sourceUrl });

export const fieldNotes: Record<string, FieldNote> = {
  '/constants': {
    year: '2019',
    title: 'Constants become exact',
    body: 'The SI redefinition fixed several constants by definition, including h, e, k, and N_A. Measurement units now rest on invariant physics rather than artifact standards.',
    ...source('BIPM, SI Brochure, 9th edition.'),
  },
  '/equations': {
    year: '1900s',
    title: 'Equations as landmarks',
    body: 'Physics keeps its deepest ideas in compact mathematical forms. A good equation page is a map of what each theory chooses to preserve, relate, or approximate.',
    ...source('Standard mathematical physics and pedagogy references.'),
  },
  '/map': {
    year: '1970s',
    title: 'Concept maps',
    body: 'Joseph Novak developed concept maps to show how ideas connect rather than listing them in sequence. Physics benefits because prerequisites form a network, not a line.',
    ...source('Joseph D. Novak and D. Bob Gowin, Learning How to Learn.'),
  },
  '/search': {
    year: '1945',
    title: "Bush's memex",
    body: 'Vannevar Bush imagined associative trails through knowledge before modern hypertext existed. Search turns a large curriculum into something navigable at the moment of need.',
    ...source('Vannevar Bush, "As We May Think."', 'https://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/'),
  },
  '/mechanics/measurement': {
    year: '1945',
    title: "Fermi's paper scraps",
    body: 'Enrico Fermi estimated the Trinity blast yield by dropping paper as the shock wave passed. It was not precision instrumentation; it was physical intuition made quantitative.',
    ...source('Richard Rhodes, The Making of the Atomic Bomb; Los Alamos historical accounts of the Trinity test.'),
  },
  '/mechanics/kinematics': {
    year: '1638',
    title: "Galileo's ramps",
    body: 'Galileo studied falling motion by slowing it down on inclined planes. The move was decisive: make nature measurable, then ask what mathematical pattern remains.',
    ...source('Galileo Galilei, Dialogues Concerning Two New Sciences.'),
  },
  '/mechanics/forces': {
    year: '1687',
    title: "Newton's Principia",
    body: 'Newton unified falling objects and planetary motion under one mechanics. The radical claim was that Earth and sky obey the same rules.',
    ...source('Isaac Newton, Philosophiæ Naturalis Principia Mathematica.'),
  },
  '/mechanics/energy': {
    year: '1840s',
    title: 'Joule and conservation',
    body: 'James Prescott Joule connected mechanical work and heat with careful experiments. Energy conservation grew from the stubborn observation that nature keeps the books.',
    ...source('James Prescott Joule, papers on the mechanical equivalent of heat; Royal Society biographical records.'),
  },
  '/mechanics/momentum': {
    year: '1600s',
    title: 'Descartes, Huygens, and impact',
    body: 'Early collision studies forced physicists to separate momentum from kinetic energy. Huygens got elastic impacts right before Newtonian notation made them familiar.',
    ...source('Christiaan Huygens, De Motu Corporum ex Percussione; René Descartes, Principles of Philosophy.'),
  },
  '/mechanics/rotation': {
    year: '1750s',
    title: "Euler's rigid bodies",
    body: 'Leonhard Euler gave rotating bodies their own equations of motion. Torque and angular momentum became more than analogies to force and momentum.',
    ...source('Leonhard Euler, Theoria Motus Corporum Solidorum seu Rigidorum.'),
  },
  '/mechanics/gravitation': {
    year: '1609',
    title: "Kepler's patient astronomy",
    body: 'Kepler extracted elliptical orbits from Tycho Brahe’s precise Mars data. Newton later explained those ellipses with universal gravitation.',
    ...source('Johannes Kepler, Astronomia Nova; Tycho Brahe observational records.'),
  },
  '/waves/oscillations': {
    year: '1656',
    title: "Huygens' pendulum clock",
    body: 'Christiaan Huygens turned the pendulum into a timekeeping machine. The same simple oscillator now appears in clocks, atoms, circuits, and quantum fields.',
    ...source('Christiaan Huygens, Horologium Oscillatorium.'),
  },
  '/waves/wave-properties': {
    year: '1700s',
    title: "d'Alembert's wave equation",
    body: "Jean le Rond d'Alembert wrote one of the first general equations for waves on a string, showing that left- and right-moving disturbances could pass through each other.",
    ...source("Jean le Rond d'Alembert, Recherches sur la courbe que forme une corde tendue mise en vibration."),
  },
  '/waves/interference': {
    year: '1801',
    title: "Young's double slit",
    body: 'Thomas Young used interference fringes to argue that light behaves like a wave. The same experiment later became a centerpiece of quantum weirdness.',
    ...source('Thomas Young, Bakerian Lectures on light and colors, Royal Society.'),
  },
  '/waves/sound': {
    year: '1842',
    title: "Doppler's moving source",
    body: 'Christian Doppler predicted that motion changes observed frequency. The idea now measures storms, galaxies, blood flow, and speeding cars.',
    ...source('Christian Doppler, Über das farbige Licht der Doppelsterne.'),
  },
  '/thermodynamics/heat': {
    year: '1798',
    title: "Rumford's cannon boring",
    body: 'Count Rumford noticed that boring cannon barrels could generate apparently endless heat. That helped undermine the old caloric-fluid picture.',
    ...source('Benjamin Thompson, Count Rumford, "An Experimental Enquiry Concerning the Source of the Heat..."'),
  },
  '/thermodynamics/gas-laws': {
    year: '1662-1811',
    title: 'The gas-law relay',
    body: 'Boyle, Charles, Gay-Lussac, and Avogadro each found part of the pattern. The ideal gas law is a compact summary of centuries of careful measurement.',
    ...source('Robert Boyle, New Experiments Physico-Mechanical; Avogadro, 1811 molecular hypothesis paper.'),
  },
  '/thermodynamics/laws': {
    year: '1824',
    title: "Carnot's engine limit",
    body: 'Sadi Carnot studied steam engines and found that efficiency has a theoretical ceiling. Industrial engineering helped reveal one of nature’s deepest laws.',
    ...source('Sadi Carnot, Reflections on the Motive Power of Fire.', 'https://www.gutenberg.org/ebooks/12725'),
  },
  '/electromagnetism/fields': {
    year: '1830s',
    title: "Faraday's lines of force",
    body: 'Faraday pictured electric and magnetic influence as fields filling space. Maxwell later turned those pictures into equations.',
    ...source('Michael Faraday, Experimental Researches in Electricity.'),
  },
  '/electromagnetism/circuits': {
    year: '1827',
    title: "Ohm's stubborn law",
    body: 'Georg Ohm’s relation between voltage, current, and resistance was not immediately celebrated. It became indispensable once electrical engineering caught up.',
    ...source('Georg Simon Ohm, Die galvanische Kette, mathematisch bearbeitet.'),
  },
  '/electromagnetism/magnetism': {
    year: '1820',
    title: "Oersted's compass needle",
    body: 'Hans Christian Oersted noticed that an electric current deflected a compass needle. Electricity and magnetism stopped being separate subjects.',
    ...source('Hans Christian Oersted, Experiments on the Effect of a Current of Electricity on the Magnetic Needle.'),
  },
  '/electromagnetism/induction': {
    year: '1831',
    title: "Faraday's induction ring",
    body: 'Faraday showed that a changing current could induce another current. Generators, transformers, and much of modern power infrastructure trace back to that insight.',
    ...source('Michael Faraday, Experimental Researches in Electricity, first series on electromagnetic induction.'),
  },
  '/optics/geometric': {
    year: '1020s',
    title: "Ibn al-Haytham's optics",
    body: 'Ibn al-Haytham argued that vision comes from light entering the eye, not rays emitted by it. His experiments helped make optics an empirical science.',
    ...source('Ibn al-Haytham, Kitab al-Manazir (Book of Optics).'),
  },
  '/optics/wave-optics': {
    year: '1818',
    title: "Fresnel's bright spot",
    body: 'Fresnel’s wave theory predicted a bright spot at the center of a circular shadow. The surprising confirmation helped defeat the purely corpuscular view of light.',
    ...source('Augustin-Jean Fresnel, diffraction memoirs; French Academy of Sciences Poisson spot episode.'),
  },
  '/modern/relativity': {
    year: '1905',
    title: "Einstein's clock problem",
    body: 'Special relativity grew from taking Maxwell’s equations and synchronized clocks seriously. Space and time had to bend to keep light speed fixed.',
    ...source('Albert Einstein, "On the Electrodynamics of Moving Bodies."', 'https://einsteinpapers.press.princeton.edu/vol2-trans/154'),
  },
  '/modern/quantum': {
    year: '1900',
    title: "Planck's desperate constant",
    body: 'Planck introduced energy quanta to fit blackbody radiation. What began as a mathematical fix became the opening move of quantum theory.',
    ...source('Max Planck, Nobel lecture and papers on blackbody radiation.', 'https://www.nobelprize.org/prizes/physics/1918/planck/lecture/'),
  },
  '/modern/atomic': {
    year: '1913',
    title: "Bohr's atom",
    body: 'Bohr combined Rutherford’s nucleus with Planck’s quantization to explain hydrogen spectra. The model was wrong in detail but right enough to open the door.',
    ...source('Niels Bohr, "On the Constitution of Atoms and Molecules."', 'https://www.nobelprize.org/prizes/physics/1922/bohr/lecture/'),
  },
  '/math/vectors': {
    year: '1800s',
    title: 'Gibbs and vector notation',
    body: 'Josiah Willard Gibbs helped popularize the compact vector notation used in physics today. Before that, many calculations were buried in quaternion language.',
    ...source('J. Willard Gibbs and E. B. Wilson, Vector Analysis.'),
  },
  '/math/calculus': {
    year: '1660s',
    title: 'Newton and Leibniz',
    body: 'Calculus was invented to describe changing quantities. Physics gave it a purpose: motion, force, fields, and accumulation all needed a new language.',
    ...source('Newton, Method of Fluxions; Leibniz, Nova Methodus pro Maximis et Minimis.'),
  },
  '/math/differential-equations': {
    year: '1700s',
    title: 'Equations of change',
    body: 'Differential equations became the grammar of physics because laws usually describe local rates of change, not finished answers.',
    ...source('History of the Euler, Bernoulli, and d’Alembert development of differential equations in mechanics.'),
  },
  '/mechanics/lagrangian': {
    year: '1788',
    title: "Lagrange's analytic mechanics",
    body: 'Lagrange rewrote mechanics without drawing every force. The principle of stationary action became one of the most durable ideas in theoretical physics.',
    ...source('Joseph-Louis Lagrange, Mecanique Analytique.'),
  },
  '/mechanics/hamiltonian': {
    year: '1830s',
    title: "Hamilton's phase space",
    body: 'Hamilton recast mechanics in terms of coordinates and momenta. That framework later became the natural bridge to statistical mechanics and quantum theory.',
    ...source('William Rowan Hamilton, papers on a general method in dynamics.'),
  },
  '/mechanics/chaos': {
    year: '1890',
    title: "Poincare's three-body surprise",
    body: 'Henri Poincare found that deterministic equations can still produce motion too sensitive to predict long-term. Chaos was hiding inside classical mechanics.',
    ...source('Henri Poincare, work on the three-body problem and Les Methodes Nouvelles de la Mecanique Celeste.'),
  },
  '/waves/fourier': {
    year: '1822',
    title: "Fourier's heat analysis",
    body: 'Fourier claimed complicated functions could be built from sine and cosine waves. The idea looked suspicious at first and then became everywhere.',
    ...source('Joseph Fourier, Theorie analytique de la chaleur.'),
  },
  '/waves/wave-equation': {
    year: '1740s',
    title: 'Strings and equations',
    body: "The vibrating string problem pushed Euler, d'Alembert, and Bernoulli toward partial differential equations. Music helped invent modern mathematical physics.",
    ...source("d'Alembert, Euler, and Daniel Bernoulli papers on vibrating strings."),
  },
  '/thermodynamics/statistical': {
    year: '1870s',
    title: "Boltzmann's counting",
    body: 'Boltzmann connected entropy to the number of microscopic arrangements. The formula on his tombstone says that disorder can be counted.',
    ...source('Ludwig Boltzmann, lectures and papers on gas theory and entropy.'),
  },
  '/thermodynamics/phases': {
    year: '1870s',
    title: "Gibbs' phase rule",
    body: 'Gibbs showed how equilibrium phases obey mathematical constraints. His work made chemistry and thermodynamics speak the same language.',
    ...source('J. Willard Gibbs, On the Equilibrium of Heterogeneous Substances.'),
  },
  '/electromagnetism/maxwell': {
    year: '1865',
    title: "Maxwell's synthesis",
    body: 'Maxwell added the displacement current and found electromagnetic waves moving at light speed. Light became an electromagnetic phenomenon.',
    ...source('James Clerk Maxwell, A Dynamical Theory of the Electromagnetic Field.'),
  },
  '/electromagnetism/em-waves': {
    year: '1887',
    title: "Hertz makes radio waves",
    body: 'Heinrich Hertz generated and detected electromagnetic waves in the lab, confirming Maxwell’s prediction and opening the road to radio.',
    ...source('Heinrich Hertz, experiments on electromagnetic waves, 1887-1888.'),
  },
  '/electromagnetism/electrostatics': {
    year: '1840s',
    title: 'Kelvin and images',
    body: 'The method of images turns conductors into clever mirror charges. William Thomson, later Lord Kelvin, helped develop these electrostatic techniques.',
    ...source("William Thomson/Lord Kelvin, papers on electrostatics and image methods."),
  },
  '/modern/spin': {
    year: '1925',
    title: 'Spin appears',
    body: 'Uhlenbeck and Goudsmit proposed electron spin to explain spectral structure. It sounded literal at first, but quantum spin is stranger than a tiny rotating ball.',
    ...source('George Uhlenbeck and Samuel Goudsmit, electron spin proposal, Naturwissenschaften.'),
  },
  '/modern/perturbation': {
    year: '1800s',
    title: 'Small corrections, big power',
    body: 'Perturbation theory grew from celestial mechanics: planets mostly follow simple orbits, with small tugs from the others. Quantum physicists inherited the trick.',
    ...source('Celestial mechanics tradition from Lagrange, Laplace, and Poincare; standard histories of perturbation theory.'),
  },
  '/math/linear-algebra': {
    year: '1920s',
    title: 'Matrices meet quantum mechanics',
    body: 'Heisenberg’s early quantum mechanics used arrays of transition amplitudes. Matrix algebra turned out to be the right machinery for observables.',
    ...source('Werner Heisenberg, Max Born, and Pascual Jordan, matrix mechanics papers.'),
  },
  '/math/complex-analysis': {
    year: '1800s',
    title: 'Cauchy and contours',
    body: 'Complex analysis made impossible real integrals tractable by walking through the complex plane. Physics uses that detour constantly.',
    ...source('Augustin-Louis Cauchy, memoirs on complex functions and residues.'),
  },
  '/optics/lasers': {
    year: '1960',
    title: 'The first laser',
    body: 'Theodore Maiman built the first working laser using a ruby crystal. The device was once called a solution looking for a problem; now it is everywhere.',
    ...source('Theodore Maiman, "Stimulated Optical Radiation in Ruby," Nature.', 'https://doi.org/10.1038/187493a0'),
  },
  '/optics/nonlinear': {
    year: '1961',
    title: 'Second-harmonic generation',
    body: 'Soon after the laser appeared, researchers saw crystals convert red light into ultraviolet. Nonlinear optics began when light became intense enough to change matter’s response.',
    ...source('P. A. Franken et al., "Generation of Optical Harmonics," Physical Review Letters.', 'https://doi.org/10.1103/PhysRevLett.7.118'),
  },
  '/optics/quantum-optics': {
    year: '1963',
    title: 'Glauber counts photons',
    body: 'Roy Glauber built a quantum theory of optical coherence. It explained what lasers do that ordinary lamps do not.',
    ...source('Roy J. Glauber, Nobel lecture and papers on optical coherence.', 'https://www.nobelprize.org/prizes/physics/2005/glauber/lecture/'),
  },
  '/optics/photonics': {
    year: '1987',
    title: 'Photonic crystals',
    body: 'Eli Yablonovitch and Sajeev John showed that periodic materials could control light the way crystals control electrons.',
    ...source('Eli Yablonovitch, "Inhibited Spontaneous Emission in Solid-State Physics and Electronics."', 'https://doi.org/10.1103/PhysRevLett.58.2059'),
  },
  '/modern/nuclear': {
    year: '1896',
    title: "Becquerel's fogged plates",
    body: 'Henri Becquerel found that uranium salts could expose photographic plates without sunlight. Radioactivity announced that atoms had hidden interiors.',
    ...source('Henri Becquerel, Comptes Rendus papers on uranium radiation.'),
  },
  '/modern/solid-state': {
    year: '1928',
    title: 'Bloch waves',
    body: 'Felix Bloch showed how electrons move through periodic crystals as waves. Band theory made conductors, insulators, and semiconductors understandable.',
    ...source('Felix Bloch, "Uber die Quantenmechanik der Elektronen in Kristallgittern."'),
  },
  '/modern/general-relativity': {
    year: '1915',
    title: "Einstein's field equations",
    body: 'General relativity replaced gravitational force with spacetime geometry. The theory first proved itself by explaining Mercury’s stubborn orbit.',
    ...source('Albert Einstein, 1915 Prussian Academy papers on general relativity.'),
  },
  '/modern/particle-physics': {
    year: '1960s-1970s',
    title: 'The Standard Model takes shape',
    body: 'Quarks, leptons, and gauge fields were assembled into a theory that predicted new particles before experiments found them.',
    ...source('Gell-Mann quark model; Glashow-Weinberg-Salam electroweak theory; standard particle physics histories.'),
  },
  '/modern/qft': {
    year: '1940s',
    title: 'Renormalization',
    body: 'Feynman, Schwinger, Tomonaga, and Dyson tamed infinities in quantum electrodynamics. The result was one of the most precise theories ever tested.',
    ...source('Feynman, Schwinger, Tomonaga, and Dyson papers on quantum electrodynamics.'),
  },
  '/modern/astrophysics': {
    year: '1920s',
    title: "Cecilia Payne's stars",
    body: 'Cecilia Payne-Gaposchkin showed that stars are mostly hydrogen and helium. A thesis result rewrote what the universe is made of.',
    ...source('Cecilia Payne-Gaposchkin, Stellar Atmospheres.'),
  },
  '/modern/cosmology': {
    year: '1929',
    title: "Hubble's expanding universe",
    body: 'Edwin Hubble found that distant galaxies recede faster. The universe stopped looking static and started having a history.',
    ...source('Edwin Hubble, "A Relation between Distance and Radial Velocity among Extra-Galactic Nebulae."', 'https://doi.org/10.1073/pnas.15.3.168'),
  },
  '/modern/quantum-info': {
    year: '1980s-1990s',
    title: 'Information becomes physical',
    body: 'Bennett, Deutsch, Shor, and others showed that quantum mechanics changes what computation and communication can mean.',
    ...source('Deutsch quantum computation; Bennett-Brassard quantum cryptography; Shor factoring algorithm papers.'),
  },
  '/modern/topological': {
    year: '1980',
    title: 'Topology enters the lab',
    body: 'The quantum Hall effect revealed electrical conductance locked to topological integers. Geometry became measurable with a voltmeter.',
    ...source('Klaus von Klitzing quantum Hall discovery; Thouless-Kohmoto-Nightingale-den Nijs topological interpretation.'),
  },
  '/modern/atomic-physics': {
    year: '1985',
    title: 'Laser cooling',
    body: 'Chu, Cohen-Tannoudji, and Phillips helped turn light into a tool for slowing atoms. Cold atoms made quantum behavior visible on human scales.',
    ...source('Nobel Prize background on laser cooling and trapping of atoms, 1997.'),
  },
  '/modern/scattering': {
    year: '1911',
    title: "Rutherford's gold foil",
    body: 'Alpha particles bouncing backward from thin gold foil revealed the atomic nucleus. Scattering became a microscope for things too small to see.',
    ...source('Ernest Rutherford, "The Scattering of alpha and beta Particles by Matter and the Structure of the Atom."', 'https://doi.org/10.1080/14786440508637080'),
  },
  '/modern/magnetism': {
    year: '1907',
    title: "Weiss' magnetic domains",
    body: 'Pierre Weiss proposed that ferromagnets contain microscopic domains. Magnetism became a collective phenomenon, not just a property of isolated atoms.',
    ...source('Pierre Weiss, papers on ferromagnetism and molecular field theory.'),
  },
  '/modern/biophysics': {
    year: '1952',
    title: 'Hodgkin and Huxley',
    body: 'Hodgkin and Huxley modeled nerve impulses with electrical circuits and ion channels. Biology became quantitative without becoming less alive.',
    ...source('A. L. Hodgkin and A. F. Huxley, 1952 Journal of Physiology paper on the squid giant axon.', 'https://doi.org/10.1113/jphysiol.1952.sp004764'),
  },
  '/modern/string-theory': {
    year: '1968',
    title: 'A formula becomes strings',
    body: 'The Veneziano amplitude was first a scattering formula. Physicists later realized it behaved as if tiny strings, not point particles, were vibrating.',
    ...source('Gabriele Veneziano, 1968 dual resonance model paper; early string theory histories.'),
  },
  '/modern/superconductivity': {
    year: '1911',
    title: 'Kamerlingh Onnes and zero resistance',
    body: 'Heike Kamerlingh Onnes cooled mercury near absolute zero and saw resistance vanish. The explanation had to wait for quantum many-body theory.',
    ...source('Heike Kamerlingh Onnes, Nobel lecture on low-temperature physics and superconductivity.', 'https://www.nobelprize.org/prizes/physics/1913/onnes/lecture/'),
  },
  '/modern/gravitational-waves': {
    year: '2015',
    title: 'LIGO hears spacetime',
    body: 'A century after Einstein predicted gravitational waves, LIGO detected the chirp of merging black holes. The signal was tiny; the implication was enormous.',
    ...source('LIGO Scientific Collaboration and Virgo Collaboration, GW150914 discovery paper.', 'https://doi.org/10.1103/PhysRevLett.116.061102'),
  },
  '/modern/many-body': {
    year: '1950s-1960s',
    title: 'Collective behavior',
    body: 'Many-body physics explains why simple microscopic rules can produce phases, quasiparticles, and emergent laws that no single particle contains.',
    ...source('P. W. Anderson, "More Is Different."', 'https://doi.org/10.1126/science.177.4047.393'),
  },
  '/modern/curved-spacetime': {
    year: '1974',
    title: "Hawking's black-hole radiation",
    body: 'Hawking combined quantum fields with curved spacetime and found that black holes should glow faintly. Gravity, quantum theory, and thermodynamics collided.',
    ...source('Stephen Hawking, "Black hole explosions?" Nature.', 'https://doi.org/10.1038/248030a0'),
  },
  '/modern/high-energy-astrophysics': {
    year: '1967',
    title: "Bell Burnell's pulsars",
    body: 'Jocelyn Bell Burnell found a strange regular radio signal that turned out to be a spinning neutron star. Precision in the noise mattered.',
    ...source('Hewish et al., "Observation of a Rapidly Pulsating Radio Source," Nature.', 'https://doi.org/10.1038/217709a0'),
  },
  '/modern/neutrino-physics': {
    year: '1956',
    title: 'The neutrino is caught',
    body: 'Cowan and Reines detected neutrinos from a reactor decades after Pauli proposed the particle to save energy conservation.',
    ...source('Cowan and Reines neutrino detection papers; Pauli 1930 neutrino proposal letter.'),
  },
  '/mechanics/fluid-mechanics': {
    year: '1738',
    title: "Bernoulli's flowing energy",
    body: 'Daniel Bernoulli connected pressure, speed, and height in moving fluids. His equation is energy conservation wearing a fluid-mechanics disguise.',
    ...source('Daniel Bernoulli, Hydrodynamica.'),
  },
  '/mechanics/plasma': {
    year: '1928',
    title: 'Langmuir names plasma',
    body: 'Irving Langmuir borrowed the word plasma for ionized gases because they carried charged particles through a collective medium.',
    ...source('Irving Langmuir, papers on oscillations in ionized gases and plasma terminology.'),
  },
  '/mechanics/elasticity': {
    year: '1678',
    title: "Hooke's spring law",
    body: "Robert Hooke's ut tensio, sic vis captured the proportionality of force and extension. Linear elasticity begins with that humble spring.",
    ...source('Robert Hooke, Lectures de Potentia Restitutiva.'),
  },
  '/mechanics/computational': {
    year: '1940s',
    title: 'Physics meets computation',
    body: 'Early electronic computers were built partly to solve physics problems too hard for pencil and paper. Simulation became a third way, beside theory and experiment.',
    ...source('ENIAC/Los Alamos computational history; Metropolis Monte Carlo papers.'),
  },
  '/thermodynamics/irreversible': {
    year: '1931',
    title: "Onsager's reciprocity",
    body: 'Lars Onsager found symmetry relations for coupled irreversible processes. Even systems out of equilibrium keep traces of microscopic reversibility.',
    ...source('Lars Onsager, "Reciprocal Relations in Irreversible Processes."', 'https://doi.org/10.1103/PhysRev.37.405'),
  },
  '/thermodynamics/nonequilibrium': {
    year: '1872',
    title: "Boltzmann's H-theorem",
    body: 'Boltzmann tried to explain why gases approach equilibrium. The argument exposed deep questions about probability, time, and what irreversibility means.',
    ...source('Ludwig Boltzmann, H-theorem papers and Lectures on Gas Theory.'),
  },
  '/thermodynamics/renormalization-group': {
    year: '1971',
    title: "Wilson's scale microscope",
    body: 'Kenneth Wilson explained critical phenomena by watching how physics changes with scale. The renormalization group became a language for universality.',
    ...source('Kenneth Wilson, renormalization group papers on critical phenomena.'),
  },
  '/thermodynamics/complex-systems': {
    year: '1980s',
    title: 'Emergence gets quantitative',
    body: 'Complex systems research asks how many simple parts produce collective behavior. The surprise is that patterns can be universal even when details differ.',
    ...source('Santa Fe Institute complex systems histories; P. W. Anderson, "More Is Different."', 'https://doi.org/10.1126/science.177.4047.393'),
  },
  '/math/probability': {
    year: '1700s',
    title: 'From games to gases',
    body: 'Probability began in gambling problems and became essential for thermodynamics, measurement, quantum theory, and inference from noisy data.',
    ...source('Pascal-Fermat correspondence; Laplace, Theorie analytique des probabilites.'),
  },
  '/math/group-theory': {
    year: '1830s',
    title: "Galois' symmetry",
    body: 'Evariste Galois connected algebraic solvability to symmetry groups. Physics later found that symmetry organizes particles, fields, and conservation laws.',
    ...source('Evariste Galois manuscripts on equations and groups; standard histories of group theory.'),
  },
  '/math/greens-functions': {
    year: '1828',
    title: "George Green's essay",
    body: 'George Green self-published work that became central to potential theory. Green’s functions now solve everything from electrostatics to quantum scattering.',
    ...source('George Green, An Essay on the Application of Mathematical Analysis to the Theories of Electricity and Magnetism.'),
  },
  '/math/tensor-calculus': {
    year: '1900s',
    title: 'The math Einstein needed',
    body: 'Ricci and Levi-Civita developed tensor calculus before general relativity. Einstein needed that language to make gravity geometric.',
    ...source('Gregorio Ricci-Curbastro and Tullio Levi-Civita, absolute differential calculus; Einstein general relativity papers.'),
  },
  '/math/special-functions': {
    year: '1800s',
    title: 'Named functions from real problems',
    body: 'Bessel, Legendre, Hermite, and others appear because common symmetries keep producing the same differential equations.',
    ...source('Classical mathematical physics literature on Bessel, Legendre, Hermite, and related special functions.'),
  },
  '/math/variational': {
    year: '1744',
    title: "Maupertuis' least action",
    body: 'The principle of least action suggested that nature follows paths selected by an extremum. Later physics made that idea astonishingly precise.',
    ...source('Maupertuis on least action; Euler and Lagrange development of variational calculus.'),
  },
};
