import {
  Definition, Theorem, WorkedExample, Step,
  PracticeProblems, Problem, InteractiveProblem, EqNumbered, Prerequisites, Takeaways, LearningGoals
} from '@/components/textbook';

export default function QuantumOpticsPage() {
  return (
    <div className="chapter">
      <div className="chapter-label" style={{ color: '#eab308' }}>Optics · Advanced Topics</div>
      <h1>Quantum Optics</h1>
      <p className="subtitle">
        Quantum optics treats the electromagnetic field itself as a quantum object.
        Coherent states, squeezed light, cavity QED, and photon entanglement
        underlie modern quantum communication, sensing, and computation.
      </p>

      <Prerequisites items={['Quantum mechanics (Ch. QM)', 'Lasers (Ch. Las)', 'Electromagnetism (Ch. EM)', 'Harmonic oscillator (Ch. QM)']} />

      <LearningGoals items={[
        'Quantise a single EM field mode as a harmonic oscillator and write the Hamiltonian in terms of creation and annihilation operators.',
        'Define Fock states and coherent states, compute their photon-number distributions, and state the uncertainty relations for the quadratures.',
        'Calculate g⁽²⁾(0) for thermal light, coherent light, and Fock state |1⟩, and interpret anti-bunching as a non-classical signature.',
        'Diagonalise the Jaynes-Cummings Hamiltonian in the one-excitation subspace and identify the vacuum Rabi splitting 2g.',
        'Describe quantum teleportation and BB84 QKD, and explain why neither violates the no-cloning theorem or allows faster-than-light signalling.',
      ]} />

      <h2>QO.1 Quantization of the Electromagnetic Field</h2>

      <p>
        Each mode (k, λ) of the EM field is a quantum harmonic oscillator.
        The vector potential is expanded in creation and annihilation operators:
      </p>

      <EqNumbered number="QO.1">A(r,t) = Σ_(k,λ) √(ℏ/(2ε₀ωV)) ε_(k,λ) [a_(k,λ) e^(ik·r−iωt) + a†_(k,λ) e^(−ik·r+iωt)]</EqNumbered>

      <p>
        Commutation: [a_(k,λ), a†_(k',λ')] = δ_(kk') δ_(λλ'). The Hamiltonian is:
        H = Σ_(k,λ) ℏω_k (a†_(k,λ) a_(k,λ) + ½) — infinite zero-point energy.
        Observable quantities involve normal-ordered products (zero-point subtracted).
      </p>

      <Definition number="QO.1" title="Fock States">
        |n⟩ = (a†)^n/√(n!) |0⟩ are eigenstates of the photon number operator N̂ = a†a
        with eigenvalue n. The vacuum |0⟩ has fluctuating electric field: ΔE = √(ℏω/(2ε₀V)) ≠ 0.
        Fock states have definite photon number but completely undefined phase.
      </Definition>

      <h2>QO.2 Coherent States</h2>

      <p>
        A coherent state |α⟩ is an eigenstate of the annihilation operator: a|α⟩ = α|α⟩,
        where α ∈ ℂ. In terms of Fock states:
      </p>

      <EqNumbered number="QO.2">|α⟩ = e^(−|α|²/2) Σ_(n=0 to ∞) α^n/√(n!) |n⟩ &nbsp;&nbsp;&nbsp; (coherent state)</EqNumbered>

      <p>
        Properties: mean photon number ⟨N̂⟩ = |α|², Poissonian statistics P(n) = e^(−|α|²)|α|^(2n)/n!,
        phase uncertainty Δφ ≈ 1/(2|α|). For |α| ≫ 1: near-classical light.
        The electric field expectation value oscillates classically: ⟨E⟩ ∝ Re(α e^(−iωt)).
      </p>

      <Theorem number="QO.1" title="Minimum Uncertainty States">
        Coherent states saturate the Heisenberg uncertainty relation for the quadratures
        X₁ = (a + a†)/2 and X₂ = (a − a†)/(2i): ΔX₁ ΔX₂ = ¼ (minimum uncertainty).
        Both quadratures have equal noise: ΔX₁ = ΔX₂ = ½ (shot noise limit).
        Squeezed states reduce noise in one quadrature below the shot noise limit
        at the expense of increased noise in the conjugate quadrature.
      </Theorem>

      <h2>QO.3 Squeezed Light</h2>

      <p>
        A squeezed state is generated by the squeezing operator S(ξ) = exp(ξ*a²/2 − ξ(a†)²/2)
        with ξ = r e^(iθ). For the squeezed vacuum:
      </p>

      <EqNumbered number="QO.3">ΔX₁ = ½ e^(−r), &nbsp;&nbsp;&nbsp; ΔX₂ = ½ e^(r) &nbsp;&nbsp;&nbsp; (squeezed quadratures, squeezing parameter r)</EqNumbered>

      <p>
        Squeezing reduces phase noise (useful for interferometry) or amplitude noise.
        <strong>LIGO</strong>: injection of squeezed light (r ≈ 15 dB achieved by 2023) into the dark port
        reduces quantum noise below the standard quantum limit — essential for detecting
        gravitational waves from binary mergers at distances &gt; 100 Mpc.
      </p>

      <p>
        Generation: optical parametric oscillator (OPO) below threshold via χ(2) process.
        Pump photon at 2ω → signal + idler at ω (two-mode squeezing) or
        degenerate OPO (single-mode squeezing).
      </p>

      <WorkedExample number="QO.1" title="Hanbury Brown–Twiss Effect and g(2)(τ)">
        <p>
          Define the second-order coherence: g(2)(τ) = ⟨a†(t) a†(t+τ) a(t+τ) a(t)⟩/⟨a†a⟩².
          Compute g(2)(0) for (a) coherent state, (b) thermal light, (c) Fock state |1⟩.
        </p>
        <Step label="Coherent state |α⟩:">⟨a†a†aa⟩ = ⟨α|a†a†aa|α⟩ = |α|⁴. ⟨a†a⟩² = |α|⁴. g(2)(0) = 1. Poissonian statistics — photons arrive randomly, uncorrelated.</Step>
        <Step label="Thermal light:">Bose-Einstein distribution gives ⟨n²⟩ = ⟨n⟩² + ⟨n⟩² (super-Poissonian). g(2)(0) = ⟨n(n−1)⟩/⟨n⟩² = 2. Photons arrive in bunches — photon bunching. HBT effect: for chaotic light, coincidences at τ=0 are twice as likely as at large τ.</Step>
        <Step label="Fock state |1⟩:">⟨1|a†a†aa|1⟩ = 0 (a|1⟩ gives |0⟩, then a|0⟩=0). g(2)(0) = 0. Perfect photon anti-bunching — one photon at a time, never two simultaneously. Signature of a single-photon emitter. g(2)(0) &lt; 1 is a quantum optical effect with no classical analog.</Step>
        <Step label="Interpretation:">g(2)(0) classifies light: bunched (thermal, &gt;1), coherent (=1), anti-bunched (&lt;1). Single-photon emitters (quantum dots, NV centers, trapped ions) show g(2)(0) ≈ 0. Measured in HBT setup: beam splitter + two detectors + coincidence counter.</Step>
      </WorkedExample>

      <h2>QO.4 Cavity QED and the Jaynes-Cummings Model</h2>

      <p>
        A two-level atom (|g⟩, |e⟩) coupled to a single cavity mode:
      </p>

      <EqNumbered number="QO.4">H_JC = ℏω_c a†a + ℏω_a σ_z/2 + ℏg(a†σ_ + aσ_+) &nbsp;&nbsp;&nbsp; (Jaynes-Cummings Hamiltonian)</EqNumbered>

      <p>
        where g is the atom-photon coupling, σ_+ = |e⟩⟨g|, σ_ = |g⟩⟨e|.
        On resonance (ω_c = ω_a): eigenstates are dressed states |±,n⟩ = (|e,n⟩ ± |g,n+1⟩)/√2
        with energies ℏω_c(n+1) ± ℏg√(n+1) — the vacuum Rabi splitting 2g for n=0.
      </p>

      <p>
        <strong>Strong coupling regime</strong>: g &gt; (κ, γ) where κ is cavity decay rate and γ is
        atomic spontaneous emission rate. Coherent quantum information exchange between
        atom and photon. <strong>Vacuum Rabi oscillations</strong>: an excited atom in an empty cavity
        oscillates between |e,0⟩ and |g,1⟩ at frequency g.
      </p>

      <p>
        <strong>Purcell effect</strong>: cavity modifies spontaneous emission rate.
        Purcell factor F_P = (3/4π²)(λ/n)³ Q/V — enhanced by high Q/V.
        F_P &gt; 1: emission enhanced (useful for bright single-photon sources).
        Applications: quantum dot in photonic crystal cavity (Q ~ 10⁶, V ~ (λ/n)³),
        superconducting qubit in microwave resonator (circuit QED, g/2π ~ 100 MHz).
      </p>

      <h2>QO.5 Entanglement and Quantum Communication</h2>

      <p>
        <strong>Bell states</strong> (polarization-entangled photon pairs from SPDC):
      </p>

      <EqNumbered number="QO.5">|Φ±⟩ = (|HH⟩ ± |VV⟩)/√2, &nbsp;&nbsp;&nbsp; |Ψ±⟩ = (|HV⟩ ± |VH⟩)/√2</EqNumbered>

      <p>
        <strong>Quantum teleportation</strong> (Bennett et al. 1993): Alice teleports state |ψ⟩ = α|H⟩ + β|V⟩
        to Bob using a shared Bell pair and two classical bits. Protocol: joint Bell measurement
        by Alice (4 outcomes) → Bob applies one of {'{'}I, X, Z, iY{'}'} conditional on outcome.
        State perfectly transferred — no cloning, no faster-than-light signaling.
      </p>

      <p>
        <strong>Quantum key distribution</strong> (QKD): BB84 protocol uses polarization states
        in two conjugate bases. Security from no-cloning theorem — eavesdropping introduces
        detectable errors (QBER &gt; 25% for full interception). Long-distance QKD via
        quantum repeaters (entanglement swapping + purification), satellite QKD (Micius, 2017,
        1200 km).
      </p>

      <Definition number="QO.2" title="Common Traps">
        <ul style={{ marginTop: '0.4rem' }}>
          <li><strong>Coherent states are not number states:</strong> they have Poisson photon-number uncertainty.</li>
          <li><strong>Squeezing moves noise between quadratures:</strong> it does not violate the uncertainty principle.</li>
          <li><strong>Entanglement is not faster-than-light signaling:</strong> correlations need classical communication to become usable information.</li>
          <li><strong>Antibunching marks nonclassical light:</strong> g⁽²⁾(0) below 1 cannot be explained by classical intensity noise.</li>
        </ul>
      </Definition>

      <PracticeProblems section="QO.1–QO.5 Quantum Optics">
        <InteractiveProblem n={1} difficulty="easy"
          answer={0.5} unit="" tolerance={0.05}
          hints={['For Fock |n⟩: g⁽²⁾(0) = ⟨n(n−1)⟩/⟨n⟩² = n(n−1)/n².', 'For |2⟩: numerator = 2×1 = 2, denominator = 2² = 4.']}
          problemText="Calculate g^(2)(0) for the Fock state |2⟩. Recall g^(2)(0) = <n(n-1)>/<n>^2."
          solution={<>Photon statistics from g(2)(0): thermal vs coherent vs Fock. Thermal light has Bose-Einstein distribution p_n = (n̄^n)/(n̄+1)^(n+1), with ⟨n⟩ = n̄ and ⟨n²⟩ = 2n̄² + n̄. Thus ⟨n(n−1)⟩ = 2n̄² and g(2)(0) = 2. Coherent state: Poissonian p_n = e^(−n̄)n̄^n/n!, so ⟨n(n−1)⟩ = n̄² and g(2)(0) = 1. Fock |2⟩: ⟨2|a†a†aa|2⟩ = ⟨2|N(N−1)|2⟩ = 2, while ⟨N⟩² = 4, so g(2)(0) = 1/2. Fock |1⟩ gives g(2)(0) = 0. Key result: g(2)(0) &lt; 1 is non-classical; g(2)(0) = 0 is perfect single-photon antibunching.</>}>
          Calculate g⁽²⁾(0) for the Fock state |2⟩. Compare the values for thermal light, coherent state, |1⟩, and |2⟩. Which are non-classical?
        </InteractiveProblem>

        <Problem n={2} difficulty="medium"
          solution={<>Vacuum Rabi splitting in cavity QED: H_JC on resonance (ω_c = ω_a = ω). In the one-excitation subspace {"|e,0⟩, |g,1⟩"}: H = ℏω(1 + σ_z/2 + a†a) projected to subspace. H_eff = ℏω(I) + ℏg[[0,1],[1,0]] = ℏωI + ℏgσ_x (in {"|e,0⟩, |g,1⟩"} basis). Eigenvalues: ℏω ± ℏg. Splitting = 2ℏg → vacuum Rabi splitting 2g/2π in Hz. For atom in a high-finesse cavity: g/2π ~ 100 MHz, κ/2π ~ 1 MHz (high-Q). Strong coupling: g ≫ κ. The two dressed-state peaks in transmission/reflection spectrum are split by 2g. For circuit QED (transmon qubit + microwave resonator): g/2π ~ 200 MHz, ω/2π ~ 5 GHz. Dispersive regime g ≪ |ω_c - ω_a|: H ≈ ℏ(ω_c + χσ_z)a†a where χ = g²/Δ (dispersive shift). State-dependent cavity frequency → qubit readout. Used in all superconducting quantum computers.</>}>
          Diagonalize the Jaynes-Cummings Hamiltonian in the one-excitation subspace. What is the vacuum Rabi splitting? How is the dispersive regime used for qubit readout in circuit QED?
        </Problem>

        <Problem n={3} difficulty="medium"
          solution={<>Quantum teleportation protocol: Initial state of system (qubit C Alice wants to send + shared Bell pair AB): |Ψ⟩ = (α|H⟩_C + β|V⟩_C) ⊗ |Φ+⟩_AB = (α|H⟩_C + β|V⟩_C) ⊗ (|HH⟩_AB + |VV⟩_AB)/√2. Rewrite C in Bell basis for CA: |Ψ⟩ = ½[|Φ+⟩_CA(α|H⟩_B + β|V⟩_B) + |Φ-⟩_CA(α|H⟩_B − β|V⟩_B) + |Ψ+⟩_CA(β|H⟩_B + α|V⟩_B) + |Ψ-⟩_CA(β|H⟩_B − α|V⟩_B)]. Alice measures CA in Bell basis (4 outcomes, 2 classical bits). Bob's state: Φ+ → I (nothing); Φ- → Z; Ψ+ → X; Ψ- → iY. Bob applies correction → |ψ⟩ = α|H⟩ + β|V⟩. Transferred exactly, no cloning (original destroyed in Bell measurement). No FTL: Bob needs classical bits before applying correction. Fidelity = 1 in principle; in practice limited by Bell state quality (CHSH violation S &lt; 2√2).</>}>
          Explain the quantum teleportation protocol step by step. Why does it not violate the no-cloning theorem or allow faster-than-light communication?
        </Problem>

        <Problem n={4} difficulty="hard"
          solution={<>Squeezed state interferometry beyond the SQL: Standard Mach-Zehnder with coherent state |α⟩ in one port, vacuum in other. Phase sensitivity: δφ_SQL = 1/√N where N = |α|². This is the shot noise limit. With squeezed vacuum in unused port (squeeze parameter r): δφ = e^(-r)/√N — reduced by e^(-r). LIGO: coherent light of power P at wavelength λ. N = P T_int/ℏω photons per measurement time T_int. SQL: δh_SQL = 1/(L√(2ωP T_int/ℏc)) where h = ΔL/L is strain. Radiation pressure noise (back-action): δh_rad = √(8ℏP T_int/(mω²L²c)). Standard quantum limit: optimize P to balance shot noise and radiation pressure. With frequency-dependent squeezing: inject squeezed phase at low f, amplitude at high f (rotation in phase space). 15 dB squeezing: e^(-r) = 10^(-15/20) ≈ 0.18, 5.6× improvement in sensitivity. Achieved at LIGO O3 run — added ~40% more detectable volume.</>}>
          Derive the phase sensitivity of a Mach-Zehnder interferometer with squeezed light input. How does LIGO use squeezed states to surpass the standard quantum limit?
        </Problem>
      </PracticeProblems>

      <Takeaways items={[
        'EM field modes are quantum oscillators. Fock |n⟩: definite photon number; coherent |α⟩: Poissonian stats, minimum uncertainty.',
        'g(2)(0): thermal=2 (bunching), coherent=1 (Poissonian), single-photon=0 (anti-bunching). Values <1 are non-classical.',
        'Squeezed light: ΔX₁=½e(-r), ΔX₂=½e(r). Reduces shot noise in one quadrature. LIGO uses 15dB squeezing.',
        'Jaynes-Cummings: two-level atom + cavity mode. Vacuum Rabi splitting 2g. Strong coupling g>(κ,γ) for coherent exchange.',
        'Purcell effect: cavity modifies spontaneous emission rate by Q/V. Used for efficient single-photon sources.',
        'Bell states, quantum teleportation, BB84 QKD — all rely on entanglement and no-cloning theorem.',
      ]} />
    </div>
  );
}
