import PhasePlotClient from '@/components/sims/PhasePlotClient';
import {
  Definition, Theorem, WorkedExample, Step,
  PracticeProblems, Problem, InteractiveProblem, EqNumbered, Figure, Prerequisites, Takeaways, LearningGoals
} from '@/components/textbook';

export default function HamiltonianPage() {
  return (
    <div className="chapter">
      <div className="chapter-label" style={{ color: '#3b82f6' }}>Classical Mechanics · Upper Division</div>
      <h1>Hamiltonian Mechanics</h1>
      <p className="subtitle">
        The Hamiltonian formulation replaces Newton&apos;s second-order equations with a symmetric
        pair of first-order equations in phase space — the natural language of statistical
        mechanics, quantum mechanics, and chaos theory.
      </p>

      <Prerequisites items={['Lagrangian mechanics (Ch. L)', 'Partial derivatives', 'Phase space concept']} />

      <LearningGoals items={[
        'Perform the Legendre transform from the Lagrangian to the Hamiltonian and write Hamilton\'s equations.',
        'Describe the harmonic oscillator phase portrait as closed ellipses at constant energy.',
        'State Liouville\'s theorem and explain its consequence for statistical mechanics ensembles.',
        'Evaluate Poisson brackets to identify conserved quantities and derive equations of motion.',
        'Construct action-angle variables for integrable systems and apply semiclassical quantization.',
      ]} />

      <h2>H.1 From Lagrangian to Hamiltonian</h2>

      <p>
        Given the Lagrangian L(q, q̇, t), the <strong>generalized momentum</strong> conjugate to
        qᵢ is defined as:
      </p>

      <EqNumbered number="H.1" latex="p_i = \frac{\partial L}{\partial \dot q_i}" />

      <p>
        The <strong>Hamiltonian</strong> is obtained by a Legendre transform that eliminates q̇
        in favor of p:
      </p>

      <EqNumbered number="H.2" latex="H(q,p,t) = \sum_i p_i\dot q_i - L(q,\dot q,t)" />

      <p>
        For a natural mechanical system (kinetic energy quadratic in velocities, no explicit time
        dependence), H equals the total mechanical energy: H = T + V.
      </p>

      <Definition number="H.1" title="Hamilton's Equations">
        The equations of motion in Hamiltonian mechanics are:
        <span style={{ display: 'block', textAlign: 'center', marginTop: '0.5rem', fontStyle: 'italic' }}>
          q̇ᵢ = ∂H/∂pᵢ &nbsp;&nbsp;&nbsp;&nbsp; ṗᵢ = −∂H/∂qᵢ
        </span>
        These replace one second-order ODE per degree of freedom with two first-order ODEs — at the
        cost of doubling the number of variables but gaining perfect symmetry between q and p.
      </Definition>

      <WorkedExample number="H.1" title="Harmonic Oscillator in Phase Space">
        <p>
          A mass m on a spring (k): L = ½mẋ² − ½kx². Write Hamilton&apos;s equations and
          describe the phase portrait.
        </p>
        <Step label="Conjugate momentum:">p = ∂L/∂ẋ = mẋ &nbsp;&nbsp; (the ordinary linear momentum)</Step>
        <Step label="Hamiltonian:">H = pẋ − L = p²/(2m) + ½kx² &nbsp;&nbsp; (kinetic + potential, as expected)</Step>
        <Step label="Hamilton's equations:">ẋ = ∂H/∂p = p/m &nbsp;&nbsp;&nbsp; ṗ = −∂H/∂x = −kx</Step>
        <Step label="Eliminating p:">ṗ = mẍ = −kx → ẍ + (k/m)x = 0 ✓ (recovers Newton)</Step>
        <Step label="Phase portrait:">H = E = const defines an ellipse in (x, p) space: x²/(2E/k) + p²/(2mE) = 1. Every orbit is a closed ellipse — the system is periodic for all energies.</Step>
      </WorkedExample>

      <h2>H.2 Phase Space and Liouville&apos;s Theorem</h2>

      <p>
        The <strong>phase space</strong> of an n-degree-of-freedom system is the 2n-dimensional
        space with coordinates (q₁,...,qₙ, p₁,...,pₙ). Each point represents a complete
        instantaneous state. Hamilton&apos;s equations define a flow in this space — every state
        has a unique future and past.
      </p>

      <Theorem number="H.1" title="Liouville's Theorem">
        The phase space flow generated by Hamilton&apos;s equations preserves volume. If you
        take a region of phase space containing many initial conditions and let the system evolve,
        the volume occupied is constant — even though the shape may distort arbitrarily:
        <span style={{ display: 'block', textAlign: 'center', marginTop: '0.5rem', fontStyle: 'italic' }}>
          dΓ/dt = 0 &nbsp;&nbsp;&nbsp; where Γ = ∫ d^n q d^n p
        </span>
        This is the foundation of statistical mechanics: a microcanonical ensemble occupies a
        constant volume in phase space. It also implies that phase space trajectories never cross.
      </Theorem>

      <Figure number="H.1" caption="Phase portraits for three Hamiltonian systems. Harmonic oscillator: perfect ellipses (all periodic). Pendulum: libration (closed curves below the separatrix), rotation (open curves above), and the separatrix itself (infinite-period orbit). Double well: two stable fixed points at ±1 with a separatrix through the unstable origin.">
        <PhasePlotClient />
      </Figure>

      <h2>H.3 Poisson Brackets</h2>

      <p>
        For any two functions f(q, p) and g(q, p), the <strong>Poisson bracket</strong> is:
      </p>

      <EqNumbered number="H.3" latex="\{f,g\} = \sum_i\left(\frac{\partial f}{\partial q_i}\frac{\partial g}{\partial p_i} - \frac{\partial f}{\partial p_i}\frac{\partial g}{\partial q_i}\right)" />

      <p>
        Poisson brackets encode the algebraic structure of classical mechanics. Key properties:
      </p>

      <EqNumbered number="H.4" latex="\{q_i,p_j\} = \delta_{ij} \qquad \{q_i,q_j\}=0 \qquad \{p_i,p_j\}=0" />

      <p>
        The time evolution of any observable A is:
      </p>

      <EqNumbered number="H.5" latex="\frac{dA}{dt} = \{A,H\} + \frac{\partial A}{\partial t}" />

      <p>
        A quantity A is conserved if and only if {'{'}A, H{'}'} = 0 (and A has no explicit time
        dependence). The Poisson bracket structure is preserved by <strong>canonical
        transformations</strong> — the symplectomorphisms that are the symmetries of Hamiltonian
        mechanics. In quantum mechanics, Poisson brackets become commutators:
        {'{'}f, g{'}'} → [f̂, ĝ]/(iℏ).
      </p>

      <WorkedExample number="H.2" title="Angular Momentum Conservation via Poisson Brackets">
        <p>
          For a central force H = p²/(2m) + V(r), show that Lz = xpy − ypx is conserved.
        </p>
        <Step label="Compute {Lz, H}:">{'{'}Lz, p²/2m{'}'} + {'{'}Lz, V(r){'}'}</Step>
        <Step label="First term:">{'{'}xpy, px²/2m{'}'} + {'{'}xpy, py²/2m{'}'} + {'{'}−ypx, ...{'}'}: evaluates to py(-px/m) + (-py)(px/m)... careful algebra gives 0.</Step>
        <Step label="Second term:">{'{'}xpy − ypx, V(r){'}'} = py ∂V/∂x − px ∂V/∂y. Since ∂V/∂x = (x/r)V&apos;(r) etc., cross terms cancel exactly.</Step>
        <Step label="Result:">{'{'}Lz, H{'}'} = 0 → Lz conserved for any central V(r). ✓ &nbsp; Angular momentum is conserved because H has no φ dependence — Noether again.</Step>
      </WorkedExample>

      <h2>H.4 Canonical Transformations and Action-Angle Variables</h2>

      <p>
        A <strong>canonical transformation</strong> (Q, P) = (Q(q,p), P(q,p)) preserves the
        form of Hamilton&apos;s equations. The condition is that the transformation preserves
        the Poisson bracket structure: {'{'}Qᵢ, Pⱼ{'}'} = δᵢⱼ.
      </p>

      <p>
        For an integrable system (as many conserved quantities as degrees of freedom), one can
        always find <strong>action-angle variables</strong> (J, θ) where:
      </p>

      <EqNumbered number="H.6" latex="J_i = \frac{1}{2\pi}\oint p_i\,dq_i \qquad \dot\theta_i = \omega_i = \frac{\partial H}{\partial J_i} = \mathrm{constant}" />

      <p>
        In action-angle variables, the Hamiltonian depends only on J, not θ — every θ is cyclic,
        every Jᵢ is conserved, and the motion is uniform rotation on a torus in phase space.
        This formulation is the starting point for perturbation theory (KAM theorem) and the
        semi-classical quantization rule: Jᵢ = nᵢ ℏ.
      </p>

      <Definition number="H.2" title="Common Traps">
        <ul style={{ marginTop: '0.4rem' }}>
          <li><strong>Hamiltonian is not always total energy:</strong> it equals energy only under standard natural-system assumptions.</li>
          <li><strong>Phase space doubles variables:</strong> q and p are independent coordinates, not position and velocity written twice.</li>
          <li><strong>Canonical transformations preserve structure:</strong> not every coordinate change preserves Poisson brackets.</li>
          <li><strong>Liouville preserves volume, not shape:</strong> a phase-space blob can stretch and fold while keeping the same volume.</li>
          <li><strong>Action-angle variables require integrability:</strong> chaotic systems generally do not admit global action-angle coordinates.</li>
        </ul>
      </Definition>

      <PracticeProblems section="H.1–H.4 Hamiltonian Mechanics">
        <InteractiveProblem n={1} difficulty="easy"
          answer={6.32} unit="rad/s" tolerance={0.02}
          hints={['Harmonic oscillator: ω = √(k/m). k=400 N/m, m=10 kg.']}
          problemText="Spring k=400 N/m, mass m=10 kg. Find natural frequency ω₀ (rad/s)."
          solution={<>ω₀ = √(400/10) = √40 = <strong>6.32 rad/s</strong></>}>
          A harmonic oscillator has spring constant k = 400 N/m and mass m = 10 kg. Find ω₀.
        </InteractiveProblem>

        <InteractiveProblem n={2} difficulty="easy"
          answer={1} unit="" tolerance={0.01}
          hints={['Liouville\'s theorem: Hamiltonian flow preserves phase space volume. The Jacobian determinant = 1.']}
          problemText="For the harmonic oscillator phase flow, what is the Jacobian determinant of the time-evolution map?"
          solution={<>By Liouville&apos;s theorem, the Jacobian = <strong>1</strong> (volume-preserving flow)</>}>
          State the Jacobian determinant of the time-evolution map for a Hamiltonian system, by Liouville's theorem.
        </InteractiveProblem>

        <Problem n={3} difficulty="easy"
          solution={<>Simple pendulum: L = ½ml²θ̇² + mgl cos θ. p = ∂L/∂θ̇ = ml²θ̇. H = pθ̇ − L = p²/(2ml²) − mgl cos θ. Hamilton&apos;s equations: θ̇ = ∂H/∂p = p/(ml²). ṗ = −∂H/∂θ = −mgl sin θ. These give ml²θ̈ = −mgl sin θ → θ̈ = −(g/l)sin θ ✓. The Hamiltonian equals the total energy: kinetic p²/(2ml²) plus potential −mgl cos θ. Fixed points: (0, 0) stable (bottom), (π, 0) unstable (top).</>}>
          Write the Hamiltonian for a simple pendulum and derive Hamilton&apos;s equations. Identify the fixed points in phase space.
        </Problem>

        <Problem n={4} difficulty="medium"
          solution={<>The action for a harmonic oscillator (H = p²/2m + mω²x²/2 = E): J = (1/2π) ∮ p dx. The orbit in phase space is an ellipse: x = A cos(ωt), p = −mωA sin(ωt), with A = √(2E/mω²). Area of ellipse = πab = π · A · mωA = πmωA² = 2πE/ω. So J = E/ω, meaning E = ωJ. The angle variable θ̇ = ∂H/∂J = ω = const ✓. Quantization: J = nℏ → E = nℏω, which is the quantum harmonic oscillator result (without zero-point energy).</>}>
          Compute the action variable J for a harmonic oscillator. Show that E = ωJ, and derive the quantization E = nℏω.
        </Problem>

        <Problem n={5} difficulty="medium"
          solution={<>Liouville verification for harmonic oscillator: the flow is (x(t), p(t)) = (x₀ cos ωt + (p₀/mω) sin ωt, −mωx₀ sin ωt + p₀ cos ωt). The Jacobian of the transformation (x₀,p₀)→(x,p) is: ∂(x,p)/∂(x₀,p₀) = the 2×2 matrix [[cos ωt, (1/mω) sin ωt], [−mω sin ωt, cos ωt]]. Determinant = cos²ωt + sin²ωt = 1. So phase space volume is exactly preserved. Liouville also follows from ∂(ẋ)/∂x + ∂(ṗ)/∂p = ∂²H/∂p∂x − ∂²H/∂x∂p = 0 (divergence-free flow).</>}>
          Verify Liouville&apos;s theorem explicitly for the harmonic oscillator by computing the Jacobian of the time-evolution map.
        </Problem>

        <Problem n={6} difficulty="hard"
          solution={<>Poisson bracket {'{'}Lx,Ly{'}'}: Lx = ypz − zpy, Ly = zpx − xpz. {'{'}Lx, Ly{'}'} = {'{'}ypz, zpx{'}'} − {'{'}ypz, xpz{'}'} − {'{'}zpy, zpx{'}'} + {'{'}zpy, xpz{'}'}. Evaluate each: {'{'}ypz, zpx{'}'} = y{'{'}pz, z{'}'}px = −ypx. {'{'}ypz, xpz{'}'} = 0. {'{'}zpy, zpx{'}'} = 0. {'{'}zpy, xpz{'}'} = z{'{'}py, pz{'}'}... = py{'{'}z, pz{'}'}x = xpy. Total: −ypx + xpy = Lz. So {'{'}Lx, Ly{'}'} = Lz. Similarly cyclic: {'{'}Ly, Lz{'}'} = Lx, {'{'}Lz, Lx{'}'} = Ly. In QM: [L̂x, L̂y] = iℏL̂z — the angular momentum commutation relations follow from the classical Poisson bracket algebra.</>}>
          Compute the Poisson bracket {'{'}Lx, Ly{'}'} for angular momentum components. Show the result equals Lz. How does this relate to quantum mechanics?
        </Problem>
      </PracticeProblems>

      <Takeaways items={[
        'Hamiltonian H = Σ pᵢq̇ᵢ − L = T + V for natural systems.',
        'Hamilton\'s equations: q̇ = ∂H/∂p, ṗ = −∂H/∂q — symmetric, first-order.',
        'Phase space flow preserves volume (Liouville\'s theorem) — phase space trajectories never cross.',
        'Poisson bracket {A,H} = 0 ↔ A is conserved. Structure mirrors quantum commutators.',
        'Canonical transformations preserve {q,p} = 1 — symplectic structure.',
        'Action-angle variables: integrable systems → uniform rotation on a torus. J = nℏ gives semiclassical quantization.',
      ]} />
    </div>
  );
}
