import {
  Definition, WorkedExample, Step,
  PracticeProblems, Problem, InteractiveProblem, EqNumbered, Prerequisites, Takeaways, LearningGoals
} from '@/components/textbook';

export default function ComplexSystemsPage() {
  return (
    <div className="chapter">
      <div className="chapter-label" style={{ color: '#f97316' }}>Thermodynamics · Advanced Topics</div>
      <h1>Complex Systems & Emergence</h1>
      <p className="subtitle">
        Complex systems — from neural networks to earthquakes to the internet —
        exhibit emergent collective behavior not reducible to their parts:
        power laws, self-organized criticality, phase transitions in networks,
        and scaling laws that transcend microscopic details.
      </p>

      <Prerequisites items={['Statistical mechanics (Ch. SM)', 'Renormalization group (Ch. RG)', 'Probability & statistics (Ch. Prob)', 'Nonlinear dynamics (Ch. Chaos)']} />

      <LearningGoals items={[
        'Identify power-law distributions on a log-log plot and explain why they have no characteristic scale, dominating statistics with rare extreme events.',
        'Describe self-organised criticality using the BTW sandpile model and explain how slow drive plus fast relaxation tunes the system to criticality without external parameter adjustment.',
        'Analyse the Kuramoto synchronisation transition and derive the critical coupling K_c = 2γ for a Lorentzian frequency distribution.',
        'Distinguish Erdős-Rényi, small-world, and scale-free network topologies and explain the percolation threshold for each.',
        'Calculate Shannon entropy for a discrete distribution and state Landauer\'s principle connecting information erasure to thermodynamic dissipation.',
      ]} />

      <h2>CS.1 Power Laws and Scale Invariance</h2>

      <p>
        Many natural distributions follow power laws: P(x) ∝ x^(−α). Unlike exponential
        distributions, power laws have no characteristic scale — they are scale-invariant.
        In a log-log plot, power laws appear as straight lines with slope −α.
      </p>

      <p>
        Examples: earthquake magnitudes (Gutenberg-Richter: log N ∝ −b M, b≈1),
        city sizes (Zipf: rank × size ≈ const), word frequencies (Zipf s=1),
        internet node degrees (Barabási-Albert: P(k) ∝ k^(−3)),
        lunar craters, wealth distributions (Pareto), solar flares, extinction events.
      </p>

      <Definition number="CS.1" title="Scale-Free Network">
        A network is scale-free if its degree distribution P(k) ∝ k^(−γ) with 2 &lt; γ &lt; 3.
        Generated by preferential attachment (Barabási-Albert): new nodes connect to
        existing nodes with probability ∝ degree. This produces hubs — nodes with
        disproportionately high degree. Scale-free networks are robust to random failure
        (hubs are unlikely to fail) but fragile to targeted attack on hubs.
        Examples: internet, WWW, protein interaction networks, citation networks.
      </Definition>

      <h2>CS.2 Self-Organized Criticality</h2>

      <p>
        Per Bak (1987): some systems naturally evolve to a critical state — without any
        parameter tuning — and exhibit scale-free fluctuations. The <strong>sandpile model</strong>:
        add grains one at a time; when a site exceeds a threshold, it topples and redistributes
        to neighbors. Avalanche size distribution: P(s) ∝ s^(−τ), τ ≈ 1.5.
      </p>

      <p>
        The system self-organizes to the edge of stability — a critical state with
        long-range spatial and temporal correlations. The order parameter (avalanche size)
        fluctuates on all scales simultaneously.
      </p>

      <p>
        <strong>SOC examples</strong>: earthquakes (Gutenberg-Richter), forest fires (fire size ∝ area^(−β)),
        biological evolution (Bak-Sneppen: fitness of weakest species drives avalanche of co-evolution),
        neural avalanches (Beggs and Plenz 2003: cascade sizes power-law distributed in cortex),
        financial markets (volatility clustering, fat tails).
      </p>

      <WorkedExample number="CS.1" title="Gutenberg-Richter Law and Energy Release">
        <p>
          Analyze the Gutenberg-Richter (GR) law for earthquake statistics and extract
          the total seismic energy release rate.
        </p>
        <Step label="GR law:">log₁₀ N(&gt;M) = a − bM where M is Richter magnitude, N(&gt;M) is the number of earthquakes exceeding magnitude M per year globally. Empirically: b ≈ 1.0 (varies from 0.8 to 1.2 by region), a ≈ 8.2 globally.</Step>
        <Step label="Energy-magnitude relation:">Seismic energy E ∝ 10^(1.5M) (Richter/Gutenberg relation: log E = 4.8 + 1.5M in erg). For M=6: E ≈ 6.3×10¹³ J ≈ 15 kiloton TNT. For M=9: E ≈ 2×10¹⁸ J (Sumatra 2004).</Step>
        <Step label="Power-law distribution:">Probability P(E) dE ∝ N(M) dM. Since M ∝ log E: P(E) ∝ E^(−(1+2b/3)) = E^(−(1+2/3)) = E^(−5/3) for b=1. Exponent α = 1 + 2b/3 ≈ 5/3.</Step>
        <Step label="Total energy:">⟨E_total⟩ = ∫E P(E) dE ∝ ∫ E^(−5/3+1) dE = ∫ E^(−2/3) dE — diverges at large E! The total seismic energy is dominated by rare, large earthquakes. 80% of Earth's seismic energy is released in M&gt;7.5 events. This is a hallmark of power-law distributions: moments can diverge, and statistics are dominated by extremes.</Step>
      </WorkedExample>

      <h2>CS.3 Network Theory</h2>

      <p>
        <strong>Erdős-Rényi (ER) random graph</strong>: N nodes, each pair connected with probability p.
        Giant component appears at p = 1/N (percolation threshold). Degree distribution: Poisson P(k) = e^(-⟨k⟩)⟨k⟩^k/k!.
      </p>

      <p>
        <strong>Small-world networks</strong> (Watts-Strogatz): start from regular ring lattice,
        randomly rewire fraction p of edges. For small p: high clustering coefficient C (like regular)
        + small average path length L (like random). The six degrees of separation arises from
        the small-world property. C ∝ (1−p)³, L ~ N/(⟨k⟩) × f(p⟨k⟩).
      </p>

      <EqNumbered number="CS.1">⟨L⟩ ~ ln N / ln⟨k⟩ &nbsp;&nbsp;&nbsp; (small-world: L grows logarithmically with N)</EqNumbered>

      <p>
        <strong>Percolation theory</strong>: fraction p of edges present. At critical p_c,
        a giant connected component (GCC) appears. Order parameter: GCC size S ∝ (p−p_c)^β.
        Correlation length: ξ ∝ |p−p_c|^(−ν). In 2D percolation the exponents are
        β=5/36 and ν=4/3; this is the q=1 Potts universality class, distinct from 2D Ising.
      </p>

      <h2>CS.4 Emergence and Collective Behavior</h2>

      <p>
        <strong>Flocking</strong> (Vicsek model): N self-propelled particles with velocity v₀,
        align with neighbors within radius r, add noise η. Order parameter: φ = (1/(Nv₀))|Σ v_i|.
        Second-order phase transition in 2D from disorder (high η or low density) to
        ordered flock (low η, high density). Continuous transition in 2D violates Mermin-Wagner!
        (resolved: activity breaks time-reversal, enabling long-range order).
      </p>

      <p>
        <strong>Kuramoto model</strong>: N coupled oscillators with natural frequencies ω_i
        (drawn from a Lorentzian distribution with width γ):
      </p>

      <EqNumbered number="CS.2">dθ_i/dt = ω_i + (K/N) Σ_j sin(θ_j − θ_i) &nbsp;&nbsp;&nbsp; (Kuramoto model)</EqNumbered>

      <p>
        Order parameter: r = (1/N)|Σ e^(iθ_j)|. Phase transition at K_c = 2γ:
        for K &lt; K_c, r = 0 (incoherent); for K &gt; K_c, r &gt; 0 (partial synchrony).
        r ∝ √(K − K_c) near K_c — mean-field critical behavior.
        Applications: firefly synchrony, cardiac pacemaker cells, power grid stability,
        Josephson junction arrays, circadian rhythms.
      </p>

      <h2>CS.5 Information Theory and Entropy</h2>

      <p>
        <strong>Shannon entropy</strong>: H = −Σ_i p_i log₂ p_i (bits). Maximum H = log₂ N
        for uniform distribution. Minimum H = 0 for deterministic system.
      </p>

      <EqNumbered number="CS.3">I(X;Y) = H(X) + H(Y) − H(X,Y) &nbsp;&nbsp;&nbsp; (mutual information — shared information between X and Y)</EqNumbered>

      <p>
        <strong>Kolmogorov complexity</strong>: K(x) = length of shortest program that outputs x.
        K(x) ≤ |x| + O(1). A random string has K(x) ≈ |x| (incompressible).
        Connection to physics: Boltzmann entropy S = k_B ln Ω relates to the number of
        microstates; Shannon entropy H relates to the information needed to specify a microstate.
        Landauer&apos;s principle: erasing 1 bit costs ≥ k_B T ln 2 of energy — information is physical.
      </p>

      <Definition number="CS.2" title="Common Traps">
        <ul style={{ marginTop: '0.4rem' }}>
          <li><strong>Power laws are not proven by one log-log line:</strong> finite data can mimic scaling over a narrow range.</li>
          <li><strong>Scale-free does not mean fully connected:</strong> most nodes can have low degree while hubs dominate connectivity.</li>
          <li><strong>Self-organized criticality requires slow drive and fast relaxation:</strong> continuous forcing can destroy the critical state.</li>
          <li><strong>Information entropy depends on probabilities:</strong> a biased source carries less uncertainty per symbol than a uniform one.</li>
        </ul>
      </Definition>

      <PracticeProblems section="CS.1–CS.5 Complex Systems">
        <Problem n={1} difficulty="easy"
          solution={<>Percolation threshold on a 2D square lattice: site percolation p_c ≈ 0.5927 (bond p_c = 0.5). For the ER random graph with N nodes and mean degree ⟨k⟩ = pN: giant component appears at ⟨k⟩ = 1 (i.e., p_c = 1/N). Below p_c: largest component ~ ln N. Above p_c: GCC size grows linearly with N, with order parameter S/N rising approximately as ⟨k⟩−1 near threshold. At criticality: GCC ~ N^(2/3). ER percolation has mean-field exponents such as β=1 and γ=1. The phase transition analogy: GCC = order parameter, p = control parameter, p_c = critical point. For scale-free networks (BA model with γ=3): p_c → 0 as N→∞ — highly robust to random failure because hubs dominate connectivity.</>}>
          Describe the percolation phase transition in a random (Erdős-Rényi) network. What is the critical threshold and how does the giant connected component grow above it?
        </Problem>

        <Problem n={2} difficulty="medium"
          solution={<>Kuramoto model synchronization transition: Order parameter r(t) = (1/N)|Σ_j e^(iθ_j)|. Mean-field: each oscillator feels the mean field re^(iψ). dθ_i/dt = ω_i + Kr sin(ψ−θ_i). Locked oscillators satisfy |ω_i| ≤ Kr and phase-lock at θ_i = ψ + arcsin(ω_i/(Kr)); drifting oscillators rotate. Self-consistency gives K_c = 2/[πg(0)]. For Lorentzian g(ω) = γ/(π(ω²+γ²)), g(0)=1/(πγ), so <strong>K_c = 2γ</strong>. For K &gt; K_c, r = √(1 − K_c/K), so near threshold r ∝ √(K−K_c) with mean-field exponent β=1/2. For N→∞ the transition is sharp; finite N gives fluctuations and nonzero residual r below K_c. Applications: firefly synchronization, cardiac pacemaker cells, and power-grid generator phase locking.</>}>
          Analyze the Kuramoto model synchronization transition. Derive the critical coupling K_c = 2γ for a Lorentzian frequency distribution. Give two physical applications.
        </Problem>

        <InteractiveProblem n={3} difficulty="medium"
          answer={0.469} unit="bits" tolerance={0.05}
          hints={['Shannon entropy: H = −p log₂p − (1−p) log₂(1−p). With p = 0.9.', 'log₂(0.9) = ln(0.9)/ln(2) ≈ −0.152; log₂(0.1) ≈ −3.322. Compute H = 0.9×0.152 + 0.1×3.322.']}
          problemText="Calculate the Shannon entropy H (bits) of a biased coin with P(heads) = 0.9."
          solution={<>Shannon entropy and Landauer's principle. Shannon entropy H = -Σ p_i log₂ p_i for a discrete source. Maximum entropy: uniform distribution P = {'{'}1/N,...,1/N{'}'} → H_max = log₂ N bits. A fair coin: H = 1 bit. 8-sided die: H = log₂(8) = 3 bits. Biased coin (p=0.9): H = -0.9 log₂(0.9) - 0.1 log₂(0.1) = 0.9×0.152 + 0.1×3.32 = 0.137 + 0.332 = 0.469 bits. Much less — nearly predictable. Landauer: erasing 1 bit of information releases at minimum k_B T ln 2 of heat to the environment. At T=300K: k_B T ln 2 = 1.38×10⁻²³ × 300 × 0.693 = 2.87×10⁻²¹ J = 0.018 eV. Modern transistors dissipate ~10⁻¹⁶ J per operation — 10⁵ times the Landauer limit. As computers shrink, they approach the limit. Maxwell's demon (1867): demon sorts fast/slow molecules → reduces entropy → violates 2nd law? Resolution (Szilard 1929, Landauer 1961): the demon must erase its memory → dissipates k_B T ln 2 per bit → no net entropy decrease. Information erasure is irreversible (not measurement).</>}>
          Calculate the Shannon entropy (bits) for a biased coin (p = 0.9). State Landauer&apos;s principle and estimate the minimum energy cost of one bit erasure at room temperature.
        </InteractiveProblem>

        <Problem n={4} difficulty="hard"
          solution={<>SOC and the Bak-Tang-Wiesenfeld (BTW) sandpile: define z_i = number of grains at site i. Toppling rule: if z_i ≥ 4 (for 2D square lattice), z_i → z_i - 4, each neighbor z_j → z_j + 1 (open boundary: grains at edge fall off). Add grains randomly one at a time. Self-organization: system drives to average slope ≈ z_c - 1 = 3 (just below threshold). An avalanche: local perturbation propagates until no site exceeds threshold. Avalanche size distribution: P(s) ~ s^(-τ) with τ ≈ 1 in 2D (controversial: log corrections make pure power law hard to verify). Mean avalanche area A ∝ s^(1/D) where D ≈ 2.5 is the fractal dimension of avalanche clusters. Linear size: ℓ ∝ s^(1/Dw) where Dw ≈ 1.25. Distinguishing SOC from criticality: SOC tunes itself via dissipation at boundary — the slow drive (grain addition rate) and fast relaxation (toppling) are key. If drive = dissipation rate: stationary state is critical. No external parameter tuned — contrast with equilibrium critical point (tune T = T_c). Connection to RG: SOC fixed point is scale-invariant but non-equilibrium. Field theory: Manna universality class for stochastic rules, BTW universality class for deterministic. Active matter systems (Vicsek model) also show SOC-like power laws in some regimes.</>}>
          Describe the BTW sandpile model and explain why it self-organizes to a critical state. What determines the avalanche size exponent? How does SOC differ from a tuned critical point?
        </Problem>
      </PracticeProblems>

      <Takeaways items={[
        'Power laws P(x) ∝ x^(-α) are scale-invariant. Log-log linear. Common in nature: earthquakes, cities, networks.',
        'SOC: systems drive themselves to criticality without tuning. Sandpile → avalanche P(s) ∝ s^(-τ). Key: slow drive, fast relaxation.',
        'Scale-free networks: P(k) ∝ k^(-γ) from preferential attachment. Robust to random failure; fragile to hub attacks.',
        'Kuramoto model: K_c = 2γ for Lorentzian. Synchronization transition: r ∝ √(K−K_c). Mean-field β = ½.',
        'Percolation: giant component at p_c = 1/N for ER graph. Same universality as magnetic phase transitions.',
        'Landauer principle: erasing 1 bit costs ≥ k_B T ln 2. Connects information entropy to thermodynamic entropy.',
      ]} />
    </div>
  );
}
